# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Sean Feeney
copyright: cc by-nc-sa
title: Sean Feeney - Silicon Desert Trailblazer
description: Sean Feeney is a transformational Silicon Desert leader.
keywords: sean, feeney, sean feeney, bio, resume, tech, technology, software, engineer, engineering, 2.0, 3.0, minneapolis, web site, website, blog, photo, video, videos, chat, projects, portfolio, home page, homepage
lang: en-US
google_analytics: UA-936138-1

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://feeney.mba" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title:output_ext

logo: /assets/img/gravatar.jpg

twitter_username: SeanFromIT
facebook_username: seanfromit
linkedin_username: seanfromit
github_username: SeanFromIT
stack_overflow_username: 311393/seanfromit
angellist_username: seanfromit
slideshare_username: SeanFeeney3

twitter:
  username: SeanFromIT
  card: summary

social:
  name: Sean Feeney
  links:
    - https://twitter.com/SeanFromIT
    - https://www.facebook.com/seanfromit
    - https://www.linkedin.com/in/seanfromit
    - https://plus.google.com/+SeanFeeneyForOffice
    - https://github.com/SeanFromIT
    - https://angel.co/seanfromit
    - https://stackexchange.com/users/311393/seanfromit
    - https://www.slideshare.net/SeanFeeney3

# Custom Data Types
collections:
  - works
  - press

# Build settings
#incremental: true
markdown: kramdown
sass:
  style: compressed
#theme: alembic-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
