---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _works
  label: Works
  create: all
  match: "**/*"
- type: directory
  path: _press
  label: Press
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
