---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _works
  label: Works
  create: all
  match: "**/*"
- type: directory
  path: _press
  label: Press
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:filename:"
